Remove duplicated title
Droogans/unmaintainable-code pull request #30
Opened 2016-12-15 14:33 UTC by dfvalero

2016-12-15 15:10 UTC, Droogans requested changes

2016-12-15 15:10 UTC, Droogans commented on README.md
>  use `define` statements to make made up functions that simply comment out their arguments, e.g.:
Can you go ahead and capitalize this too?

2016-12-16 09:21 UTC, dfvalero commented on README.md
>  use `define` statements to make made up functions that simply comment out their arguments, e.g.:
sure

2016-12-16 17:54 UTC, Droogans approved these changes

2016-12-16 17:54 UTC, Droogans commented
Cool avatar. Thanks!

2016-12-16 17:54 UTC, merged